# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: galaxy_game_development
  host: db
  username: postgres
  password: password

# Test database - completely separate from development
test:
  <<: *default
  database: galaxy_game_test
  host: db
  username: postgres
  password: password

production:
  <<: *default
  database: galaxy_game_production
  username: galaxy_game
  password: <%= ENV['GALAXY_GAME_DATABASE_PASSWORD'] %>
